git clone git@github.com:doocs/advanced-java.git doocs#advanced-java
git clone git@github.com:dragonslayerx/Competitive-Programming-Repository.git dragonslayerx#Competitive-Programming-Repository
git clone git@github.com:dropwizard/dropwizard.git dropwizard#dropwizard
git clone git@github.com:dropwizard/metrics.git dropwizard#metrics
git clone git@github.com:e-maxx-eng/e-maxx-eng.git e-maxx-eng#e-maxx-eng
git clone git@github.com:EbTech/rust-algorithms.git EbTech#rust-algorithms
git clone git@github.com:eclipse/eclipse-collections.git eclipse#eclipse-collections
git clone git@github.com:eclipse-vertx/vert.git eclipse-vertx#vert
git clone git@github.com:eka-foundation/numerical-computing-is-fun.git eka-foundation#numerical-computing-is-fun
git clone git@github.com:elarity/data-structure-php-clanguage.git elarity#data-structure-php-clanguage
git clone git@github.com:elastic/elasticsearch.git elastic#elasticsearch
git clone git@github.com:elastic/logstash.git elastic#logstash
git clone git@github.com:eliangcs/http-prompt.git eliangcs#http-prompt
git clone git@github.com:emmanueltouzery/prelude-ts.git emmanueltouzery#prelude-ts
git clone git@github.com:encode/django-rest-framework.git encode#django-rest-framework
git clone git@github.com:ethereumjs/merkle-patricia-tree.git ethereumjs#merkle-patricia-tree
git clone git@github.com:EvgenyKarkan/EKAlgorithms.git EvgenyKarkan#EKAlgorithms
git clone git@github.com:evolve75/RubyTree.git evolve75#RubyTree
git clone git@github.com:expede/algae.git expede#algae
git clone git@github.com:explosion/spaCy.git explosion#spaCy
git clone git@github.com:facebook/buck.git facebook#buck
git clone git@github.com:facebook/infer.git facebook#infer
git clone git@github.com:facebook/prophet.git facebook#prophet
git clone git@github.com:facert/awesome-spider.git facert#awesome-spider
git clone git@github.com:facert/python-data-structure-cn.git facert#python-data-structure-cn
git clone git@github.com:faheel/Algos.git faheel#Algos
git clone git@github.com:faif/python-patterns.git faif#python-patterns
git clone git@github.com:fastai/fastai.git fastai#fastai
git clone git@github.com:felipernb/algorithms.git felipernb#algorithms
git clone git@github.com:FiguredLimited/vue-mc.git FiguredLimited#vue-mc
git clone git@github.com:fishercoder1534/Leetcode.git fishercoder1534#Leetcode
git clone git@github.com:flaggo/pydu.git flaggo#pydu
git clone git@github.com:florent37/MaterialViewPager.git florent37#MaterialViewPager
git clone git@github.com:floyernick/Data-Structures-and-Algorithms.git floyernick#Data-Structures-and-Algorithms
git clone git@github.com:flyway/flyway.git flyway#flyway
git clone git@github.com:fmela/libdict.git fmela#libdict
git clone git@github.com:fragglet/c-algorithms.git fragglet#c-algorithms
git clone git@github.com:francistao/LearningNotes.git francistao#LearningNotes
git clone git@github.com:FreeTymeKiyan/LeetCode-Sol-Res.git FreeTymeKiyan#LeetCode-Sol-Res
git clone git@github.com:frptools/collectable.git frptools#collectable
git clone git@github.com:funkia/list.git funkia#list
git clone git@github.com:getpelican/pelican.git getpelican#pelican
git clone git@github.com:getredash/redash.git getredash#redash
git clone git@github.com:GokuMohandas/practicalAI.git GokuMohandas#practicalAI
git clone git@github.com:google/android-classyshark.git google#android-classyshark
git clone git@github.com:google/error-prone.git google#error-prone
git clone git@github.com:google/ExoPlayer.git google#ExoPlayer
git clone git@github.com:google/flatbuffers.git google#flatbuffers
git clone git@github.com:google/guava.git google#guava
git clone git@github.com:google/python-fire.git google#python-fire
git clone git@github.com:google/tink.git google#tink
git clone git@github.com:google/yapf.git google#yapf
git clone git@github.com:GoogleContainerTools/jib.git GoogleContainerTools#jib
git clone git@github.com:graphhopper/jsprit.git graphhopper#jsprit
git clone git@github.com:gunthercox/ChatterBot.git gunthercox#ChatterBot
git clone git@github.com:gyuho/goraph.git gyuho#goraph
git clone git@github.com:gyuho/learn.git gyuho#learn
git clone git@github.com:gzu-liyujiang/AndroidPicker.git gzu-liyujiang#AndroidPicker
git clone git@github.com:h2oai/h2o-3.git h2oai#h2o-3
git clone git@github.com:hangtwenty/dive-into-machine-learning.git hangtwenty#dive-into-machine-learning
git clone git@github.com:hankcs/AhoCorasickDoubleArrayTrie.git hankcs#AhoCorasickDoubleArrayTrie
git clone git@github.com:HelloZeroNet/ZeroNet.git HelloZeroNet#ZeroNet
git clone git@github.com:home-assistant/home-assistant.git home-assistant#home-assistant
git clone git@github.com:hosseinmoein/DataFrame.git hosseinmoein#DataFrame
git clone git@github.com:hs-web/hsweb-framework.git hs-web#hsweb-framework
git clone git@github.com:huge-success/sanic.git huge-success#sanic
git clone git@github.com:huihut/interview.git huihut#interview
git clone git@github.com:hustcc/JS-Sorting-Algorithm.git hustcc#JS-Sorting-Algorithm
git clone git@github.com:ibaaj/dijkstra-cartography.git ibaaj#dijkstra-cartography
git clone git@github.com:ignoreintuition/jSchema.git ignoreintuition#jSchema
git clone git@github.com:iiitv/algos.git iiitv#algos
git clone git@github.com:iluwatar/java-design-patterns.git iluwatar#java-design-patterns
git clone git@github.com:im95able/Rea.git im95able#Rea
git clone git@github.com:imhuay/Algorithm_Interview_Notes-Chinese.git imhuay#Algorithm_Interview_Notes-Chinese
git clone git@github.com:inamiy/Cassowary.git inamiy#Cassowary
git clone git@github.com:inconvergent/differential-line.git inconvergent#differential-line
git clone git@github.com:indy256/codelibrary.git indy256#codelibrary
git clone git@github.com:infinit/elle.git infinit#elle
git clone git@github.com:ipython/ipython.git ipython#ipython
git clone git@github.com:ityouknow/spring-boot-examples.git ityouknow#spring-boot-examples
git clone git@github.com:jack-pappas/ExtCore.git jack-pappas#ExtCore
git clone git@github.com:jainaman224/Algo_Ds_Notes.git jainaman224#Algo_Ds_Notes
git clone git@github.com:jakevdp/PythonDataScienceHandbook.git jakevdp#PythonDataScienceHandbook
git clone git@github.com:jakubroztocil/httpie.git jakubroztocil#httpie
git clone git@github.com:jamesroutley/write-a-hash-table.git jamesroutley#write-a-hash-table
git clone git@github.com:japaric/heapless.git japaric#heapless
git clone git@github.com:jayshah19949596/CodingInterviews.git jayshah19949596#CodingInterviews
git clone git@github.com:JCTools/JCTools.git JCTools#JCTools
git clone git@github.com:jdneo/vscode-leetcode.git jdneo#vscode-leetcode
git clone git@github.com:jeffgerickson/algorithms.git jeffgerickson#algorithms
git clone git@github.com:jenkinsci/jenkins.git jenkinsci#jenkins
git clone git@github.com:jflinter/Dwifft.git jflinter#Dwifft
git clone git@github.com:jgrapht/jgrapht.git jgrapht#jgrapht
git clone git@github.com:jhipster/generator-jhipster.git jhipster#generator-jhipster
git clone git@github.com:jhy/jsoup.git jhy#jsoup
git clone git@github.com:jimmysuncpt/Algorithms.git jimmysuncpt#Algorithms
git clone git@github.com:JodaOrg/joda-time.git JodaOrg#joda-time
git clone git@github.com:joelittlejohn/jsonschema2pojo.git joelittlejohn#jsonschema2pojo
git clone git@github.com:joke2k/faker.git joke2k#faker
git clone git@github.com:joowani/binarytree.git joowani#binarytree
