git clone git@github.com:judasn/IntelliJ-IDEA-Tutorial.git judasn#IntelliJ-IDEA-Tutorial
git clone git@github.com:JuliaCollections/DataStructures.git JuliaCollections#DataStructures
git clone git@github.com:jumpserver/jumpserver.git jumpserver#jumpserver
git clone git@github.com:justcoding121/Advanced-Algorithms.git justcoding121#Advanced-Algorithms
git clone git@github.com:justjavac/free-programming-books-zh_CN.git justjavac#free-programming-books-zh_CN
git clone git@github.com:jwasham/coding-interview-university.git jwasham#coding-interview-university
git clone git@github.com:jwtk/jjwt.git jwtk#jjwt
git clone git@github.com:kamyu104/LintCode.git kamyu104#LintCode
git clone git@github.com:kanaka/mal.git kanaka#mal
git clone git@github.com:kaushikgopal/RxJava-Android-Samples.git kaushikgopal#RxJava-Android-Samples
git clone git@github.com:kdn251/interviews.git kdn251#interviews
git clone git@github.com:kennethreitz/requests.git kennethreitz#requests
git clone git@github.com:kennethreitz/requests-html.git kennethreitz#requests-html
git clone git@github.com:keon/algorithms.git keon#algorithms
git clone git@github.com:keras-team/keras.git keras-team#keras
git clone git@github.com:kivy/kivy.git kivy#kivy
git clone git@github.com:knightsj/awesome-algorithm-question-solution.git knightsj#awesome-algorithm-question-solution
git clone git@github.com:Konloch/bytecode-viewer.git Konloch#bytecode-viewer
git clone git@github.com:kth-competitive-programming/kactl.git kth-competitive-programming#kactl
git clone git@github.com:leandrotk/algorithms.git leandrotk#algorithms
git clone git@github.com:libgdx/libgdx.git libgdx#libgdx
git clone git@github.com:lihengming/spring-boot-api-project-seed.git lihengming#spring-boot-api-project-seed
git clone git@github.com:lionsoul2014/ip2region.git lionsoul2014#ip2region
git clone git@github.com:lithammer/fuzzysearch.git lithammer#fuzzysearch
git clone git@github.com:liuyubobobo/Play-with-Data-Structures.git liuyubobobo#Play-with-Data-Structures
git clone git@github.com:liyifeng1994/ssm.git liyifeng1994#ssm
git clone git@github.com:ljvmiranda921/pyswarms.git ljvmiranda921#pyswarms
git clone git@github.com:lnishan/awesome-competitive-programming.git lnishan#awesome-competitive-programming
git clone git@github.com:locustio/locust.git locustio#locust
git clone git@github.com:loiane/javascript-datastructures-algorithms.git loiane#javascript-datastructures-algorithms
git clone git@github.com:lucaong/immutable.git lucaong#immutable
git clone git@github.com:LukeLin/js-stl.git LukeLin#js-stl
git clone git@github.com:lyfeyaj/awesome-resources.git lyfeyaj#awesome-resources
git clone git@github.com:machinelearningmindset/TensorFlow-Course.git machinelearningmindset#TensorFlow-Course
git clone git@github.com:mahmoud/awesome-python-applications.git mahmoud#awesome-python-applications
git clone git@github.com:mahmoud/boltons.git mahmoud#boltons
git clone git@github.com:mandliya/algorithms_and_data_structures.git mandliya#algorithms_and_data_structures
git clone git@github.com:mapbox/delaunator.git mapbox#delaunator
git clone git@github.com:mapbox/earcut.git mapbox#earcut
git clone git@github.com:mapbox/supercluster.git mapbox#supercluster
git clone git@github.com:marcosfede/algorithms.git marcosfede#algorithms
git clone git@github.com:marioyc/Online-Judge-Solutions.git marioyc#Online-Judge-Solutions
git clone git@github.com:matthewsamuel95/ACM-ICPC-Algorithms.git matthewsamuel95#ACM-ICPC-Algorithms
git clone git@github.com:mauriciosantos/Buckets-JS.git mauriciosantos#Buckets-JS
git clone git@github.com:mcxiaoke/packer-ng-plugin.git mcxiaoke#packer-ng-plugin
git clone git@github.com:medcl/elasticsearch-analysis-ik.git medcl#elasticsearch-analysis-ik
git clone git@github.com:meolu/walle-web.git meolu#walle-web
git clone git@github.com:mgechev/javascript-algorithms.git mgechev#javascript-algorithms
git clone git@github.com:micropython/micropython.git micropython#micropython
git clone git@github.com:Microsoft/CNTK.git Microsoft#CNTK
git clone git@github.com:Microsoft/LightGBM.git Microsoft#LightGBM
git clone git@github.com:mikepenz/Android-Iconics.git mikepenz#Android-Iconics
git clone git@github.com:mikepenz/MaterialDrawer.git mikepenz#MaterialDrawer
git clone git@github.com:Miserlou/Zappa.git Miserlou#Zappa
git clone git@github.com:mithi/robotics-coursework.git mithi#robotics-coursework
git clone git@github.com:mitmproxy/mitmproxy.git mitmproxy#mitmproxy
git clone git@github.com:mkdocs/mkdocs.git mkdocs#mkdocs
git clone git@github.com:MLEveryday/100-Days-Of-ML-Code.git MLEveryday#100-Days-Of-ML-Code
git clone git@github.com:mockito/mockito.git mockito#mockito
git clone git@github.com:mostafa-saad/ArabicCompetitiveProgramming.git mostafa-saad#ArabicCompetitiveProgramming
git clone git@github.com:mourner/flatbush.git mourner#flatbush
git clone git@github.com:mourner/rbush.git mourner#rbush
git clone git@github.com:muwenzi/Program-Blog.git muwenzi#Program-Blog
git clone git@github.com:mxgmn/ConvChain.git mxgmn#ConvChain
git clone git@github.com:mxgmn/TextureSynthesis.git mxgmn#TextureSynthesis
git clone git@github.com:mxgmn/WaveFunctionCollapse.git mxgmn#WaveFunctionCollapse
git clone git@github.com:mybatis/mybatis-3.git mybatis#mybatis-3
git clone git@github.com:Mybridge/machine-learning-open-source.git Mybridge#machine-learning-open-source
git clone git@github.com:NAU-ACM/ACM-ICPC-Preparation.git NAU-ACM#ACM-ICPC-Preparation
git clone git@github.com:naver/pinpoint.git naver#pinpoint
git clone git@github.com:nicolargo/glances.git nicolargo#glances
git clone git@github.com:NLPchina/ansj_seg.git NLPchina#ansj_seg
git clone git@github.com:nltk/nltk.git nltk#nltk
git clone git@github.com:no-stack-dub-sack/cs-playground-react.git no-stack-dub-sack#cs-playground-react
git clone git@github.com:nonstriater/Learn-Algorithms.git nonstriater#Learn-Algorithms
git clone git@github.com:norvig/pytudes.git norvig#pytudes
git clone git@github.com:numpy/numpy.git numpy#numpy
git clone git@github.com:nvbn/thefuck.git nvbn#thefuck
git clone git@github.com:odoo/odoo.git odoo#odoo
git clone git@github.com:OlafenwaMoses/ImageAI.git OlafenwaMoses#ImageAI
git clone git@github.com:OmkarPathak/Data-Structures-using-Python.git OmkarPathak#Data-Structures-using-Python
git clone git@github.com:OmkarPathak/pygorithm.git OmkarPathak#pygorithm
git clone git@github.com:open-android/Android.git open-android#Android
git clone git@github.com:OpenFeign/feign.git OpenFeign#feign
git clone git@github.com:OpenGenus/cosmos.git OpenGenus#cosmos
git clone git@github.com:OpenRefine/OpenRefine.git OpenRefine#OpenRefine
git clone git@github.com:oracle/graal.git oracle#graal
git clone git@github.com:orhanobut/dialogplus.git orhanobut#dialogplus
git clone git@github.com:orhanobut/logger.git orhanobut#logger
git clone git@github.com:orium/rpds.git orium#rpds
git clone git@github.com:orsinium/textdistance.git orsinium#textdistance
git clone git@github.com:pallets/click.git pallets#click
git clone git@github.com:pallets/flask.git pallets#flask
git clone git@github.com:pandas-dev/pandas.git pandas-dev#pandas
git clone git@github.com:pathikrit/scalgos.git pathikrit#scalgos
git clone git@github.com:patrickfav/BlurTestAndroid.git patrickfav#BlurTestAndroid
git clone git@github.com:peferron/algo.git peferron#algo
git clone git@github.com:PegasusWang/python_data_structures_and_algorithms.git PegasusWang#python_data_structures_and_algorithms
git clone git@github.com:permissions-dispatcher/PermissionsDispatcher.git permissions-dispatcher#PermissionsDispatcher
git clone git@github.com:PetarV-/Algorithms.git PetarV-#Algorithms
