git clone git@github.com:PhilJay/MPAndroidChart.git PhilJay#MPAndroidChart
git clone git@github.com:phishman3579/java-algorithms-implementation.git phishman3579#java-algorithms-implementation
git clone git@github.com:php-ds/ext-ds.git php-ds#ext-ds
git clone git@github.com:pirate/crypto-trader.git pirate#crypto-trader
git clone git@github.com:playframework/playframework.git playframework#playframework
git clone git@github.com:plotly/dash.git plotly#dash
git clone git@github.com:postmanlabs/httpbin.git postmanlabs#httpbin
git clone git@github.com:powerline/powerline.git powerline#powerline
git clone git@github.com:prestodb/presto.git prestodb#presto
git clone git@github.com:prolificinteractive/material-calendarview.git prolificinteractive#material-calendarview
git clone git@github.com:pypa/pipenv.git pypa#pipenv
git clone git@github.com:python-telegram-bot/python-telegram-bot.git python-telegram-bot#python-telegram-bot
git clone git@github.com:pytorch/pytorch.git pytorch#pytorch
git clone git@github.com:QuantConnect/Lean.git QuantConnect#Lean
git clone git@github.com:quantopian/zipline.git quantopian#zipline
git clone git@github.com:ra1028/DifferenceKit.git ra1028#DifferenceKit
git clone git@github.com:Ramotion/folding-cell-android.git Ramotion#folding-cell-android
git clone git@github.com:rampatra/Algorithms-and-Data-Structures-in-Java.git rampatra#Algorithms-and-Data-Structures-in-Java
git clone git@github.com:RaRe-Technologies/gensim.git RaRe-Technologies#gensim
git clone git@github.com:rasbt/python-machine-learning-book.git rasbt#python-machine-learning-book
git clone git@github.com:raywenderlich/swift-algorithm-club.git raywenderlich#swift-algorithm-club
git clone git@github.com:ReactiveX/RxJava.git ReactiveX#RxJava
git clone git@github.com:real-logic/aeron.git real-logic#aeron
git clone git@github.com:realm/realm-java.git realm#realm-java
git clone git@github.com:realpython/python-guide.git realpython#python-guide
git clone git@github.com:reddit-archive/reddit.git reddit-archive#reddit
git clone git@github.com:redisson/redisson.git redisson#redisson
git clone git@github.com:rest-assured/rest-assured.git rest-assured#rest-assured
git clone git@github.com:rey5137/material.git rey5137#material
git clone git@github.com:rishabh115/Interview-Questions.git rishabh115#Interview-Questions
git clone git@github.com:robolectric/robolectric.git robolectric#robolectric
git clone git@github.com:rocketshipapps/adblockfast.git rocketshipapps#adblockfast
git clone git@github.com:roughike/BottomBar.git roughike#BottomBar
git clone git@github.com:royalpranjal/Interview-Bit.git royalpranjal#Interview-Bit
git clone git@github.com:royeo/awesome-programming-books.git royeo#awesome-programming-books
git clone git@github.com:rushter/MLAlgorithms.git rushter#MLAlgorithms
git clone git@github.com:RyanFehr/HackerRank.git RyanFehr#HackerRank
git clone git@github.com:ryanoasis/nerd-fonts.git ryanoasis#nerd-fonts
git clone git@github.com:sagivo/algorithms.git sagivo#algorithms
git clone git@github.com:saltstack/salt.git saltstack#salt
git clone git@github.com:satwikkansal/wtfpython.git satwikkansal#wtfpython
git clone git@github.com:scikit-learn/scikit-learn.git scikit-learn#scikit-learn
git clone git@github.com:scrapy/scrapy.git scrapy#scrapy
git clone git@github.com:scribejava/scribejava.git scribejava#scribejava
git clone git@github.com:SeleniumHQ/selenium.git SeleniumHQ#selenium
git clone git@github.com:selfboot/CS_Offer.git selfboot#CS_Offer
git clone git@github.com:selfboot/LeetCode.git selfboot#LeetCode
git clone git@github.com:serhii-londar/open-source-mac-os-apps.git serhii-londar#open-source-mac-os-apps
git clone git@github.com:SFTtech/openage.git SFTtech#openage
git clone git@github.com:shenweichen/Coursera.git shenweichen#Coursera
git clone git@github.com:shivamMg/ppds.git shivamMg#ppds
git clone git@github.com:sivel/speedtest-cli.git sivel#speedtest-cli
git clone git@github.com:skidding/illustrated-algorithms.git skidding#illustrated-algorithms
git clone git@github.com:skyhee/Algorithms-Learning-With-Go.git skyhee#Algorithms-Learning-With-Go
git clone git@github.com:skylot/jadx.git skylot#jadx
git clone git@github.com:Snailclimb/JavaGuide.git Snailclimb#JavaGuide
git clone git@github.com:soapyigu/LeetCode-Swift.git soapyigu#LeetCode-Swift
git clone git@github.com:sockeqwe/mosby.git sockeqwe#mosby
git clone git@github.com:songtianyi/acmer-qualification-code.git songtianyi#acmer-qualification-code
git clone git@github.com:spotify/luigi.git spotify#luigi
git clone git@github.com:spring-cloud-incubator/spring-cloud-alibaba.git spring-cloud-incubator#spring-cloud-alibaba
git clone git@github.com:spring-projects/spring-boot.git spring-projects#spring-boot
git clone git@github.com:sqlmapproject/sqlmap.git sqlmapproject#sqlmap
git clone git@github.com:square/leakcanary.git square#leakcanary
git clone git@github.com:srdja/Collections-C.git srdja#Collections-C
git clone git@github.com:stacygohyunsi/algorithms-primer.git stacygohyunsi#algorithms-primer
git clone git@github.com:stanch/reftree.git stanch#reftree
git clone git@github.com:StevenBlack/hosts.git StevenBlack#hosts
git clone git@github.com:SuprDewd/CompetitiveProgramming.git SuprDewd#CompetitiveProgramming
git clone git@github.com:SuprDewd/T-414-AFLV.git SuprDewd#T-414-AFLV
git clone git@github.com:SuyashLakhotia/TechInterview.git SuyashLakhotia#TechInterview
git clone git@github.com:swagger-api/swagger-core.git swagger-api#swagger-core
git clone git@github.com:Tapadoo/Alerter.git Tapadoo#Alerter
git clone git@github.com:tboox/tbox.git tboox#tbox
git clone git@github.com:tdebatty/java-string-similarity.git tdebatty#java-string-similarity
git clone git@github.com:tensorflow/tensorflow.git tensorflow#tensorflow
git clone git@github.com:Tessil/hat-trie.git Tessil#hat-trie
git clone git@github.com:Tessil/hopscotch-map.git Tessil#hopscotch-map
git clone git@github.com:Tessil/ordered-map.git Tessil#ordered-map
git clone git@github.com:Tessil/robin-map.git Tessil#robin-map
git clone git@github.com:TheAlgorithms/C-Plus-Plus.git TheAlgorithms#C-Plus-Plus
git clone git@github.com:TheAlgorithms/Java.git TheAlgorithms#Java
git clone git@github.com:TheAlgorithms/Javascript.git TheAlgorithms#Javascript
git clone git@github.com:TheAlgorithms/Python.git TheAlgorithms#Python
git clone git@github.com:TheAlgorithms/Rust.git TheAlgorithms#Rust
git clone git@github.com:timgrossmann/InstaPy.git timgrossmann#InstaPy
git clone git@github.com:timtadh/data-structures.git timtadh#data-structures
git clone git@github.com:tobegit3hub/advisor.git tobegit3hub#advisor
git clone git@github.com:tongtzeho/PKUCourse.git tongtzeho#PKUCourse
git clone git@github.com:tornadoweb/tornado.git tornadoweb#tornado
git clone git@github.com:tqdm/tqdm.git tqdm#tqdm
git clone git@github.com:trekhleb/homemade-machine-learning.git trekhleb#homemade-machine-learning
git clone git@github.com:trekhleb/javascript-algorithms.git trekhleb#javascript-algorithms
git clone git@github.com:Turfjs/turf.git Turfjs#turf
git clone git@github.com:tuvtran/project-based-learning.git tuvtran#project-based-learning
git clone git@github.com:twitter/finagle.git twitter#finagle
git clone git@github.com:VAR-solutions/Algorithms.git VAR-solutions#Algorithms
git clone git@github.com:vicky002/AlgoWiki.git vicky002#AlgoWiki
git clone git@github.com:vinta/awesome-python.git vinta#awesome-python
git clone git@github.com:vipshop/vjtools.git vipshop#vjtools
